apiVersion: v1
kind: Namespace
metadata:
  name: idp-platform
  labels:
    app.kubernetes.io/part-of: idp-platform
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: idp-platform-monitoring
  labels:
    app.kubernetes.io/part-of: idp-platform
    purpose: monitoring
