version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg14
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - '7474:7474'
      - '7687:7687'
