apiVersion: v1
kind: ServiceAccount
metadata:
  name: idp-agent
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: idp-streamlit
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: idp-ingestion
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
automountServiceAccountToken: false
